"""Nutrition Worker Agent.

Specialized agent for meal plan generation, macro calculations,
and South Asian dietary planning. Only accesses nutrition/food tools.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncGenerator

from langfuse import observe
from langfuse.openai import AsyncOpenAI
from openai import (
    APIConnectionError,
    APIStatusError,
    AuthenticationError,
    RateLimitError,
)

from app.core.ai_cache import AICache, get_ai_cache
from app.core.ai_metrics import ai_metrics
from app.core.config import settings
from app.core.logging import get_logger
from app.schemas.ai_context import UserAIContext
from app.services.agents.base import BaseWorker, WorkerDomain
from app.services.loop_guard import AgentLoopGuard, MaxIterationsExceededError

logger = get_logger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────

_MAX_STREAM_CHUNKS = 2000
_MOCK_CHUNK_DELAY = 0.02

_OPENAI_ERRORS = (
    RateLimitError,
    APIConnectionError,
    AuthenticationError,
    APIStatusError,
)

_CONTEXT_HEADER = "# USER CONTEXT — Persistent facts. Always respect these constraints."

# ── System Prompt ──────────────────────────────────────────────────────────

# Single source of truth for the meal-plan system prompt lives in
# ai_service.SYSTEM_PROMPT (with the strict South Asian / Desi mandate).
# Importing it here keeps the /ai streaming route and the orchestrator
# worker from drifting apart.
from app.services.ai_service import SYSTEM_PROMPT as NUTRITION_SYSTEM_PROMPT

# ── Sandbox Mock Content ───────────────────────────────────────────────────

_MOCK_MEAL_PLAN = """# Authentic South Asian High-Protein Meal Plan

> 🧪 **Sandbox Mode** — This plan was generated by the local fallback model. For AI-personalised plans, add a valid OpenAI API key.

## 📋 Daily Summary

| Nutrient | Target | Planned |
|----------|--------|---------|
| Calories | 2,200 kcal | 2,195 kcal |
| Protein | 120 g | 128 g |
| Carbs | 250 g | 245 g |
| Fat | 65 g | 67 g |

---

## 🌅 Breakfast — Anda Bhurji with Roti (540 kcal)

| Food | Portion | Cal | Protein | Carbs | Fat |
|------|---------|-----|---------|-------|-----|
| Anda bhurji (spiced scrambled eggs) | 3 eggs | 240 | 18 g | 4 g | 16 g |
| Whole wheat roti | 2 medium | 200 | 6 g | 36 g | 3.5 g |
| Butter (for cooking) | 1 tsp | 34 | 0 g | 0 g | 3.8 g |
| Green chili + coriander | garnish | 6 | 0.3 g | 1 g | 0.1 g |
| Masala chai (with milk) | 1 cup | 60 | 2 g | 8 g | 2.5 g |

**Meal Total:** 540 kcal · 26 g protein · 49 g carbs · 26 g fat

---

## ☀️ Lunch — Chicken Tikka with Basmati Rice (680 kcal)

| Food | Portion | Cal | Protein | Carbs | Fat |
|------|---------|-----|---------|-------|-----|
| Chicken tikka (grilled, marinated) | 200 g | 330 | 46 g | 2 g | 14 g |
| Basmati rice (cooked) | 1.5 cups (285 g) | 345 | 7 g | 72 g | 0.5 g |
| Raita (yogurt + cucumber) | ½ cup | 60 | 3 g | 5 g | 2.5 g |
| Kachumber salad | 1 bowl | 40 | 1.5 g | 8 g | 0.2 g |

**Meal Total:** 680 kcal · 57 g protein · 87 g carbs · 17 g fat

---

## 🌆 Snack — Roasted Chana & Almonds (280 kcal)

| Food | Portion | Cal | Protein | Carbs | Fat |
|------|---------|-----|---------|-------|-----|
| Roasted chana (chickpeas) | ½ cup (60 g) | 200 | 10 g | 27 g | 4 g |
| Almonds | 8 pieces (12 g) | 70 | 2.5 g | 2.5 g | 6 g |
| Green tea | 1 cup | 2 | 0 g | 0 g | 0 g |

**Meal Total:** 280 kcal · 13 g protein · 30 g carbs · 10 g fat

---

## 🌙 Dinner — Dal Makhani with Roti & Palak Paneer (695 kcal)

| Food | Portion | Cal | Protein | Carbs | Fat |
|------|---------|-----|---------|-------|-----|
| Dal makhani (black lentil curry) | 1.5 cups | 310 | 16 g | 40 g | 8 g |
| Whole wheat roti | 2 medium | 200 | 6 g | 36 g | 3.5 g |
| Palak paneer | 1 cup | 185 | 12 g | 8 g | 12 g |
| Basmati rice (side) | ½ cup (100 g) | 130 | 2.7 g | 28 g | 0.3 g |

**Meal Total:** 695 kcal · 37 g protein · 112 g carbs · 24 g fat

---

## 💡 Tips

1. **Hydration** — Aim for 3–4 litres of water daily; add lemon slices for flavour
2. **Meal Prep** — Batch-cook chicken tikka and dal makhani on Sunday for the week
3. **Protein Timing** — Consume a protein shake within 30 minutes post-workout for optimal recovery
4. **Fibre** — The roti, dal, and chana provide ~22 g of dietary fibre (73% daily target)
"""


# ── Worker Implementation ──────────────────────────────────────────────────


class NutritionWorker(BaseWorker):
    """Specialized worker for meal plan and nutrition generation.

    Tools & capabilities:
    - Meal plan generation (South Asian cuisine)
    - Macro calculation and tracking
    - Food library search
    - Dietary preference handling (halal, vegetarian, allergies)
    """

    @property
    def domain(self) -> WorkerDomain:
        return WorkerDomain.NUTRITION

    @property
    def description(self) -> str:
        return "Meal plans, macro tracking, dietary preferences, and South Asian food library"

    @property
    def keywords(self) -> list[str]:
        return [
            "meal", "food", "diet", "nutrition", "calories", "protein",
            "carbs", "fat", "macro", "biryani", "chicken", "daal", "roti",
            "breakfast", "lunch", "dinner", "snack", "vegetarian", "vegan",
            "halal", "keto", "allergy", "eat", "recipe", "portion",
            "weight loss", "cut", "bulk", "tdee", "bmr",
        ]

    def matches_intent(self, user_message: str) -> float:
        """Enhanced matching for nutrition-specific queries."""
        base_score = super().matches_intent(user_message)
        # Boost score for explicit meal plan requests
        if any(phrase in user_message.lower() for phrase in [
            "meal plan", "what should i eat", "meal plan for",
            "create a meal", "generate a meal", "food plan",
        ]):
            return min(base_score + 0.3, 1.0)
        return base_score

    @observe()
    async def generate_stream(
        self,
        user_message: str,
        user_context: UserAIContext | None = None,
        **kwargs,
    ) -> AsyncGenerator[str, None]:
        """Generate a meal plan stream.

        Keyword Args:
            target_calories: Daily calorie target.
            protein_g: Daily protein target in grams.
            dietary_preferences: List of dietary preferences.
            allergies: List of allergies to exclude.
            cuisine_type: Preferred cuisine type.
        """
        api_key = settings.openai_api_key
        model = settings.openai_model

        if not api_key:
            logger.warning("[NutritionWorker] OPENAI_API_KEY not configured — sandbox fallback")
            async for chunk in self._stream_sandbox(_MOCK_MEAL_PLAN):
                yield chunk
            yield "data: [DONE]\n\n"
            return

        # Build the user message from kwargs or the raw message
        system_prompt = self._merge_context(NUTRITION_SYSTEM_PROMPT, user_context)
        user_content = self._build_user_content(user_message, kwargs)

        # ── Cache lookup: identical targets/cuisine/prefs within the cache
        # window are served without spending LLM tokens. ───────────────────
        cache = get_ai_cache()
        cache_key = AICache.build_key(
            target_calories=kwargs.get("target_calories"),
            protein_g=kwargs.get("protein_g"),
            cuisine_type=kwargs.get("cuisine_type"),
            dietary_preferences=kwargs.get("dietary_preferences"),
            allergies=kwargs.get("allergies"),
            user_context=user_context,
        )
        cached = cache.get(cache_key)
        if cached is not None:
            cached_text, served_as_variation = cached
            if served_as_variation:
                cached_text = (
                    f"{cached_text}\n\n---\n*Variation note: this plan was regenerated from a "
                    "recently created plan for your exact targets. Adjust spices/portions "
                    "to taste — or change a target slightly for a fresh plan.*"
                )
            ai_metrics.record_cache_hit(len(cached_text))
            async for chunk in self._stream_cached(cached_text):
                yield chunk
            yield "data: [DONE]\n\n"
            return

        logger.info(
            "[NutritionWorker] Streaming: calories=%s protein=%s context=%s",
            kwargs.get("target_calories"),
            kwargs.get("protein_g"),
            "yes" if user_context else "none",
        )

        guard = AgentLoopGuard(max_iterations=_MAX_STREAM_CHUNKS)
        client = AsyncOpenAI(api_key=api_key)
        full_response_parts: list[str] = []
        stream_ok = True

        try:
            stream = await client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_content},
                ],
                stream=True,
                temperature=0.7,
                max_tokens=2000,
            )
            ai_metrics.record_llm_call()

            async for chunk in stream:
                try:
                    guard.tick()
                except MaxIterationsExceededError:
                    logger.warning(
                        "[NutritionWorker] Stream terminated: budget exceeded after %d chunks",
                        guard.current,
                    )
                    yield self._sse({"error": True, "message": "Generation terminated: maximum output length reached"})
                    stream_ok = False
                    break
                delta = chunk.choices[0].delta if chunk.choices else None
                if delta and delta.content:
                    full_response_parts.append(delta.content)
                    yield self._sse({"text": delta.content})

        except _OPENAI_ERRORS as exc:
            stream_ok = False
            logger.exception(
                "[NutritionWorker] OpenAI API unavailable (%s) — sandbox fallback",
                type(exc).__name__,
            )
            async for chunk in self._stream_sandbox(_MOCK_MEAL_PLAN):
                yield chunk

        except Exception:
            stream_ok = False
            logger.exception("[NutritionWorker] Unexpected error during streaming")
            async for chunk in self._stream_sandbox(_MOCK_MEAL_PLAN):
                yield chunk

        # Only cache complete, non-empty generations — partial streams and
        # sandbox fallbacks must never poison the cache.
        if stream_ok:
            full_response = "".join(full_response_parts)
            if full_response.strip():
                cache.put(cache_key, full_response)

        yield "data: [DONE]\n\n"

    # ── Internal Helpers ───────────────────────────────────────────────

    def _merge_context(self, base: str, context: UserAIContext | None) -> str:
        """Merge user context into the system prompt."""
        if context is None:
            return base
        block = context.format_for_prompt()
        if not block:
            return base
        return f"{base}\n\n{_CONTEXT_HEADER}\n{block}"

    def _build_user_content(self, raw_message: str, kwargs: dict) -> str:
        """Build structured user content from raw message and kwargs."""
        parts: list[str] = []

        if kwargs.get("target_calories"):
            parts.append(f"- Target calories: {kwargs['target_calories']:.0f} kcal/day")
        if kwargs.get("protein_g"):
            parts.append(f"- Target protein: {kwargs['protein_g']:.0f}g/day")
        if kwargs.get("dietary_preferences"):
            parts.append(f"- Dietary preferences: {', '.join(kwargs['dietary_preferences'])}")
        if kwargs.get("allergies"):
            parts.append(f"- Allergies to exclude: {', '.join(kwargs['allergies'])}")
        if kwargs.get("cuisine_type"):
            parts.append(f"- Preferred cuisine: {kwargs['cuisine_type']}")
        else:
            # Always pin the cuisine explicitly — an omitted field must never
            # leave the model free to drift toward generic Western meals.
            parts.append("- Preferred cuisine: South Asian (Desi)")

        if parts:
            return "Create a 1-day meal plan with the following requirements:\n" + "\n".join(parts) + "\n\n" + raw_message
        return raw_message

    async def _stream_cached(self, text: str) -> AsyncGenerator[str, None]:
        """Yield a cached response as SSE chunks (fast — no artificial delay)."""
        chunk_size = 64
        for i in range(0, len(text), chunk_size):
            yield self._sse({"text": text[i : i + chunk_size]})

    async def _stream_sandbox(self, text: str) -> AsyncGenerator[str, None]:
        """Yield text in chunks for mock streaming."""
        yield self._sse({"sandbox": True, "text": ""})
        chunk_size = 8
        for i in range(0, len(text), chunk_size):
            yield self._sse({"text": text[i : i + chunk_size]})
            await asyncio.sleep(_MOCK_CHUNK_DELAY)

    @staticmethod
    def _sse(data: dict) -> str:
        """Format data as an SSE line."""
        return f"data: {json.dumps(data)}\n\n"
