"""Nutrition Worker Agent.

Specialized agent for meal plan generation, macro calculations,
and South Asian dietary planning. Only accesses nutrition/food tools.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncGenerator

from langfuse import observe
from langfuse.openai import AsyncOpenAI
from openai import (
    APIConnectionError,
    APIStatusError,
    AuthenticationError,
    RateLimitError,
)

from app.core.config import settings
from app.core.logging import get_logger
from app.schemas.ai_context import UserAIContext
from app.services.agents.base import BaseWorker, WorkerDomain
from app.services.loop_guard import AgentLoopGuard, MaxIterationsExceededError

logger = get_logger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────

_MAX_STREAM_CHUNKS = 2000
_MOCK_CHUNK_DELAY = 0.02

_OPENAI_ERRORS = (
    RateLimitError,
    APIConnectionError,
    AuthenticationError,
    APIStatusError,
)

_CONTEXT_HEADER = "# USER CONTEXT — Persistent facts. Always respect these constraints."

# ── System Prompt ──────────────────────────────────────────────────────────

NUTRITION_SYSTEM_PROMPT = """You are an expert South Asian fitness nutritionist. Generate detailed,
practical meal plans based on the user's requirements. Focus on foods commonly
available in South Asian cuisine (Pakistan, India, Bangladesh, Nepal, Sri Lanka).

For each meal, provide:
- Meal name and type (breakfast, lunch, dinner, snack)
- Specific foods with portion sizes
- Approximate calories, protein, carbs, and fat per food
- Daily totals

Format your response as structured JSON inside a Markdown code block:
```json
{
  "meals": [
    {
      "type": "breakfast",
      "name": "...",
      "foods": [
        {"name": "...", "portion": "...", "calories": 0, "protein_g": 0, "carbs_g": 0, "fat_g": 0}
      ],
      "meal_calories": 0,
      "meal_protein_g": 0,
      "meal_carbs_g": 0,
      "meal_fat_g": 0
    }
  ],
  "daily_totals": {"calories": 0, "protein_g": 0, "carbs_g": 0, "fat_g": 0},
  "tips": ["..."]
}
```

Be specific with portions (e.g., "1 cup cooked rice", "150g chicken breast").
Always include at least one meal of each type: breakfast, lunch, dinner.
"""

# ── Sandbox Mock Content ───────────────────────────────────────────────────

_MOCK_MEAL_PLAN = """# High-Protein South Asian Meal Plan

> 🧪 **Sandbox Mode** — This plan was generated by the local fallback model. For AI-personalised plans, add a valid OpenAI API key.

## 📋 Daily Summary

| Nutrient | Target | Planned |
|----------|--------|---------|
| Calories | 2,200 kcal | 2,185 kcal |
| Protein | 120 g | 124 g |
| Carbs | 250 g | 242 g |
| Fat | 65 g | 68 g |

---

## 🌅 Breakfast — Desi Protein Oats (540 kcal)

| Food | Portion | Cal | Protein | Carbs | Fat |
|------|---------|-----|---------|-------|-----|
| Steel-cut oats | 1 cup (80 g) | 300 | 10 g | 54 g | 5 g |
| Milk (whole) | 1 cup (240 ml) | 150 | 8 g | 12 g | 8 g |
| Whey protein | 1 scoop (30 g) | 120 | 24 g | 3 g | 1.5 g |
| Banana | 1 medium | 105 | 1.3 g | 27 g | 0.4 g |
| Almonds | 6 pieces (10 g) | 58 | 2.1 g | 2.1 g | 5 g |

**Meal Total:** 540 kcal · 24 g protein · 52 g carbs · 12 g fat

---

## ☀️ Lunch — Chicken Tikka Brown Rice Bowl (680 kcal)

| Food | Portion | Cal | Protein | Carbs | Fat |
|------|---------|-----|---------|-------|-----|
| Chicken tikka (grilled) | 200 g | 330 | 46 g | 2 g | 14 g |
| Brown rice (cooked) | 1.5 cups (285 g) | 345 | 7.5 g | 72 g | 2.8 g |
| Raita (yogurt + cucumber) | ½ cup | 60 | 3 g | 5 g | 2.5 g |
| Mixed salad (kachumber) | 1 bowl | 40 | 1.5 g | 8 g | 0.2 g |

**Meal Total:** 680 kcal · 48 g protein · 87 g carbs · 20 g fat

---

## 🌆 Snack — Paneer Tikka Bites (310 kcal)

| Food | Portion | Cal | Protein | Carbs | Fat |
|------|---------|-----|---------|-------|-----|
| Paneer (grilled) | 100 g | 265 | 18 g | 3 g | 20 g |
| Green chutney | 2 tbsp | 15 | 0.5 g | 2 g | 0.5 g |
| Cucumber slices | 1 cup | 16 | 0.7 g | 3.5 g | 0.1 g |
| Green tea | 1 cup | 2 | 0 g | 0 g | 0 g |

**Meal Total:** 310 kcal · 19 g protein · 9 g carbs · 21 g fat

---

## 🌙 Dinner — Lentil Curry with Chapati (655 kcal)

| Food | Portion | Cal | Protein | Carbs | Fat |
|------|---------|-----|---------|-------|-----|
| Masoor dal (red lentil curry) | 1.5 cups | 290 | 18 g | 42 g | 4 g |
| Whole wheat chapati | 2 medium | 200 | 6 g | 36 g | 3.5 g |
| Palak paneer | 1 cup | 180 | 12 g | 8 g | 11 g |
| Steamed rice (basmati) | ½ cup (100 g) | 130 | 2.7 g | 28 g | 0.3 g |

**Meal Total:** 655 kcal · 33 g protein · 90 g carbs · 19 g fat

---

## 💡 Tips

1. **Hydration** — Aim for 3–4 litres of water daily; add lemon slices for flavour
2. **Meal Prep** — Batch-cook chicken tikka and brown rice on Sunday for the week
3. **Protein Timing** — Consume whey within 30 minutes post-workout for optimal recovery
4. **Fibre** — The brown rice and lentils provide ~18 g of dietary fibre (60% daily target)
"""


# ── Worker Implementation ──────────────────────────────────────────────────


class NutritionWorker(BaseWorker):
    """Specialized worker for meal plan and nutrition generation.

    Tools & capabilities:
    - Meal plan generation (South Asian cuisine)
    - Macro calculation and tracking
    - Food library search
    - Dietary preference handling (halal, vegetarian, allergies)
    """

    @property
    def domain(self) -> WorkerDomain:
        return WorkerDomain.NUTRITION

    @property
    def description(self) -> str:
        return "Meal plans, macro tracking, dietary preferences, and South Asian food library"

    @property
    def keywords(self) -> list[str]:
        return [
            "meal", "food", "diet", "nutrition", "calories", "protein",
            "carbs", "fat", "macro", "biryani", "chicken", "daal", "roti",
            "breakfast", "lunch", "dinner", "snack", "vegetarian", "vegan",
            "halal", "keto", "allergy", "eat", "recipe", "portion",
            "weight loss", "cut", "bulk", "tdee", "bmr",
        ]

    def matches_intent(self, user_message: str) -> float:
        """Enhanced matching for nutrition-specific queries."""
        base_score = super().matches_intent(user_message)
        # Boost score for explicit meal plan requests
        if any(phrase in user_message.lower() for phrase in [
            "meal plan", "what should i eat", "meal plan for",
            "create a meal", "generate a meal", "food plan",
        ]):
            return min(base_score + 0.3, 1.0)
        return base_score

    @observe()
    async def generate_stream(
        self,
        user_message: str,
        user_context: UserAIContext | None = None,
        **kwargs,
    ) -> AsyncGenerator[str, None]:
        """Generate a meal plan stream.

        Keyword Args:
            target_calories: Daily calorie target.
            protein_g: Daily protein target in grams.
            dietary_preferences: List of dietary preferences.
            allergies: List of allergies to exclude.
            cuisine_type: Preferred cuisine type.
        """
        api_key = settings.openai_api_key
        model = settings.openai_model

        if not api_key:
            logger.warning("[NutritionWorker] OPENAI_API_KEY not configured — sandbox fallback")
            async for chunk in self._stream_sandbox(_MOCK_MEAL_PLAN):
                yield chunk
            yield "data: [DONE]\n\n"
            return

        # Build the user message from kwargs or the raw message
        system_prompt = self._merge_context(NUTRITION_SYSTEM_PROMPT, user_context)
        user_content = self._build_user_content(user_message, kwargs)

        logger.info(
            "[NutritionWorker] Streaming: calories=%s protein=%s context=%s",
            kwargs.get("target_calories"),
            kwargs.get("protein_g"),
            "yes" if user_context else "none",
        )

        guard = AgentLoopGuard(max_iterations=_MAX_STREAM_CHUNKS)
        client = AsyncOpenAI(api_key=api_key)

        try:
            stream = await client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_content},
                ],
                stream=True,
                temperature=0.7,
                max_tokens=2000,
            )

            async for chunk in stream:
                try:
                    guard.tick()
                except MaxIterationsExceededError:
                    logger.warning(
                        "[NutritionWorker] Stream terminated: budget exceeded after %d chunks",
                        guard.current,
                    )
                    yield self._sse({"error": True, "message": "Generation terminated: maximum output length reached"})
                    break
                delta = chunk.choices[0].delta if chunk.choices else None
                if delta and delta.content:
                    yield self._sse({"text": delta.content})

        except _OPENAI_ERRORS as exc:
            logger.warning(
                "[NutritionWorker] OpenAI unavailable (%s: %s) — sandbox fallback",
                type(exc).__name__, exc,
            )
            async for chunk in self._stream_sandbox(_MOCK_MEAL_PLAN):
                yield chunk

        except Exception:
            logger.exception("[NutritionWorker] Unexpected error during streaming")
            async for chunk in self._stream_sandbox(_MOCK_MEAL_PLAN):
                yield chunk

        yield "data: [DONE]\n\n"

    # ── Internal Helpers ───────────────────────────────────────────────

    def _merge_context(self, base: str, context: UserAIContext | None) -> str:
        """Merge user context into the system prompt."""
        if context is None:
            return base
        block = context.format_for_prompt()
        if not block:
            return base
        return f"{base}\n\n{_CONTEXT_HEADER}\n{block}"

    def _build_user_content(self, raw_message: str, kwargs: dict) -> str:
        """Build structured user content from raw message and kwargs."""
        parts: list[str] = []

        if kwargs.get("target_calories"):
            parts.append(f"- Target calories: {kwargs['target_calories']:.0f} kcal/day")
        if kwargs.get("protein_g"):
            parts.append(f"- Target protein: {kwargs['protein_g']:.0f}g/day")
        if kwargs.get("dietary_preferences"):
            parts.append(f"- Dietary preferences: {', '.join(kwargs['dietary_preferences'])}")
        if kwargs.get("allergies"):
            parts.append(f"- Allergies to exclude: {', '.join(kwargs['allergies'])}")
        if kwargs.get("cuisine_type"):
            parts.append(f"- Preferred cuisine: {kwargs['cuisine_type']}")

        if parts:
            return "Create a 1-day meal plan with the following requirements:\n" + "\n".join(parts) + "\n\n" + raw_message
        return raw_message

    async def _stream_sandbox(self, text: str) -> AsyncGenerator[str, None]:
        """Yield text in chunks for mock streaming."""
        yield self._sse({"sandbox": True, "text": ""})
        chunk_size = 8
        for i in range(0, len(text), chunk_size):
            yield self._sse({"text": text[i : i + chunk_size]})
            await asyncio.sleep(_MOCK_CHUNK_DELAY)

    @staticmethod
    def _sse(data: dict) -> str:
        """Format data as an SSE line."""
        return f"data: {json.dumps(data)}\n\n"
