"""Workout Worker Agent.

Specialized agent for workout routine generation, training split planning,
and exercise programming. Only accesses exercise/training tools.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncGenerator

from openai import (
    APIConnectionError,
    APIStatusError,
    AsyncOpenAI,
    AuthenticationError,
    RateLimitError,
)

from app.core.config import settings
from app.core.logging import get_logger
from app.schemas.ai_context import UserAIContext
from app.services.agents.base import BaseWorker, WorkerDomain
from app.services.loop_guard import AgentLoopGuard, MaxIterationsExceededError

logger = get_logger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────

_MAX_STREAM_CHUNKS = 3000  # workouts are longer than meal plans
_MOCK_CHUNK_DELAY = 0.02

_OPENAI_ERRORS = (
    RateLimitError,
    APIConnectionError,
    AuthenticationError,
    APIStatusError,
)

_CONTEXT_HEADER = "# USER CONTEXT — Persistent facts. Always respect these constraints."

# ── System Prompt ──────────────────────────────────────────────────────────

WORKOUT_SYSTEM_PROMPT = """You are an expert South Asian fitness coach and strength & conditioning specialist.
Generate detailed, progressive-overload workout routines tailored to the user's
experience level, goals, available equipment, and training split.

For each workout day, provide:
- Day name and focus (e.g., "Day 1 — Push")
- Each exercise with:
  - Exercise name (use standard gym terminology)
  - Sets × Reps (e.g., 4 × 8-10)
  - Rest interval (e.g., 90s, 2 min)
  - Tempo if relevant (e.g., 3-1-2-0)
  - Optional notes (e.g., "focus on mind-muscle connection")
- Warm-up and cool-down for each day
- Progressive overload notes for week-over-week progression

Format your response as clean Markdown with clear headers, tables where
appropriate, and bullet points. Use this structure:

# [Goal] Workout Program
## Overview
- Split type, duration, frequency
- Progressive overload strategy
## Day 1 — [Focus]
### Warm-up
### Working Sets
| Exercise | Sets × Reps | Rest | Notes |
|----------|-------------|------|-------|
| ... | ... | ... | ... |
### Cool-down
## Day 2 — [Focus]
...
## Weekly Progression Notes
- Week 1: ... (introduction)
- Week 2: ... (volume increase)
- Week 3: ... (intensity increase)
- Week 4: ... (deload)

Be specific, practical, and evidence-based. Include rep ranges that match
the user's experience level.
"""

# ── Sandbox Mock Content ───────────────────────────────────────────────────

_MOCK_WORKOUT = """# Push / Pull / Legs — Hypertrophy Program

> 🧪 **Sandbox Mode** — This program was generated by the local fallback model. For AI-personalised routines, add a valid OpenAI API key.

## Overview

- **Split:** Push / Pull / Legs (6-day rotation)
- **Frequency:** 5–6 days/week
- **Focus:** Muscle Hypertrophy
- **Duration:** 4-week mesocycle
- **Progressive Overload:** +2.5 kg compound / +1–2 reps accessory each week

---

## Day 1 — Push (Chest, Shoulders, Triceps)

### Warm-up
- 5 min incline treadmill walk
- Band pull-aparts: 2 × 15
- Dumbbell lateral raises: 2 × 12 (light)

### Working Sets

| Exercise | Sets × Reps | Rest | Notes |
|----------|-------------|------|-------|
| Barbell Bench Press | 4 × 8–10 | 2 min | Controlled eccentric 3 sec |
| Incline Dumbbell Press | 3 × 10–12 | 90 sec | Full ROM, squeeze at top |
| Cable Flyes (low-to-high) | 3 × 12–15 | 60 sec | Slow negative |
| Overhead Press (barbell) | 4 × 8–10 | 2 min | No leg drive |
| Lateral Raises | 3 × 15–20 | 45 sec | Slight lean forward |
| Tricep Pushdowns | 3 × 12–15 | 60 sec | Rope attachment |
| Overhead Tricep Extension | 3 × 10–12 | 60 sec | Dumbbell, full stretch |

### Cool-down
- Chest doorway stretch: 2 × 30 sec each side
- Tricep overhead stretch: 2 × 30 sec
- Foam roll upper back: 2 min

---

## Day 2 — Pull (Back, Biceps, Rear Delts)

### Warm-up
- 5 min rowing machine (easy pace)
- Cat-cow stretches: 2 × 10
- Band face pulls: 2 × 15

### Working Sets

| Exercise | Sets × Reps | Rest | Notes |
|----------|-------------|------|-------|
| Deadlift (conventional) | 4 × 6–8 | 2.5 min | Belt up at 80%+ |
| Weighted Pull-ups | 4 × 8–10 | 2 min | Add weight when > 10 reps |
| Barbell Bent-Over Row | 3 × 8–10 | 90 sec | Overhand grip |
| Seated Cable Row | 3 × 12–15 | 60 sec | Squeeze scapulae |
| Face Pulls | 3 × 15–20 | 45 sec | External rotation at top |
| Barbell Curl | 3 × 10–12 | 60 sec | No swinging |
| Hammer Curl | 3 × 12 | 45 sec | Alternating arms |

### Cool-down
- Lat stretch (hanging from bar): 2 × 30 sec
- Bicep wall stretch: 2 × 20 sec each arm
- Foam roll lats: 2 min

---

## Day 3 — Legs (Quads, Hamstrings, Glutes, Calves)

### Warm-up
- 5 min bike (moderate)
- Bodyweight squats: 2 × 15
- Leg swings: 2 × 10 each direction

### Working Sets

| Exercise | Sets × Reps | Rest | Notes |
|----------|-------------|------|-------|
| Barbell Back Squat | 4 × 8–10 | 2.5 min | Below parallel |
| Romanian Deadlift | 4 × 10–12 | 2 min | Hamstring stretch at bottom |
| Bulgarian Split Squat | 3 × 10–12/leg | 90 sec | Hold dumbbells |
| Leg Press | 3 × 12–15 | 90 sec | Feet high and wide for glutes |
| Leg Curl (lying) | 3 × 12–15 | 60 sec | Slow eccentric |
| Standing Calf Raise | 4 × 15–20 | 45 sec | Full stretch at bottom |
| Seated Calf Raise | 3 × 15–20 | 45 sec | Pause at top |

### Cool-down
- Quad stretch: 2 × 30 sec each
- Hamstring door stretch: 2 × 30 sec each
- Pigeon pose: 2 × 30 sec each side
- Foam roll quads/hamstrings: 3 min

---

## 📈 Weekly Progression Notes

- **Week 1 (Introduction):** Use RPE 7–8 weights. Focus on form and mind-muscle connection. Record baseline numbers.
- **Week 2 (Volume Increase):** Add 1 extra set to compound lifts OR add 2 reps to each working set. Maintain same weight.
- **Week 3 (Intensity Increase):** Increase weight by 2.5 kg on compounds (squat, bench, deadlift, OHP) and 1–2.5 kg on accessories. Keep reps the same.
- **Week 4 (Deload):** Reduce weight to 60% of week 3. Reduce volume by ~40%. Focus on recovery and mobility. Prepare for next mesocycle.

---

## 🥗 Nutrition Reminder

- **Protein:** Aim for 1.6–2.2 g per kg of body weight daily
- **Hydration:** 3+ litres of water per day
- **Sleep:** 7–9 hours for optimal recovery
"""


# ── Worker Implementation ──────────────────────────────────────────────────


class WorkoutWorker(BaseWorker):
    """Specialized worker for workout routine generation.

    Tools & capabilities:
    - Workout plan generation (strength, hypertrophy, endurance, fat loss)
    - Training split programming (PPL, Upper/Lower, Full Body)
    - Exercise selection and progressive overload
    - Equipment-aware programming
    """

    @property
    def domain(self) -> WorkerDomain:
        return WorkerDomain.WORKOUT

    @property
    def description(self) -> str:
        return "Workout routines, training splits, exercises, and progressive overload"

    @property
    def keywords(self) -> list[str]:
        return [
            "workout", "exercise", "training", "gym", "strength", "hypertrophy",
            "endurance", "cardio", "squat", "bench", "deadlift", "pull",
            "push", "legs", "split", "routine", "program", "sets", "reps",
            "progressive overload", "muscle", "fitness", "coach", "train",
            "bodyweight", "dumbbells", "barbell",
        ]

    def matches_intent(self, user_message: str) -> float:
        """Enhanced matching for workout-specific queries."""
        base_score = super().matches_intent(user_message)
        # Boost score for explicit workout requests
        if any(phrase in user_message.lower() for phrase in [
            "workout plan", "training plan", "exercise routine",
            "create a workout", "generate a workout", "workout for",
        ]):
            return min(base_score + 0.3, 1.0)
        return base_score

    async def generate_stream(
        self,
        user_message: str,
        user_context: UserAIContext | None = None,
        **kwargs,
    ) -> AsyncGenerator[str, None]:
        """Generate a workout plan stream.

        Keyword Args:
            goal: Training goal (strength, hypertrophy, endurance, fat_loss).
            experience_level: User experience (beginner, intermediate, advanced).
            split: Training split (upper_lower, push_pull_legs, full_body).
            equipment: Available equipment (gym, bodyweight, dumbbells).
        """
        api_key = settings.openai_api_key
        model = settings.openai_model

        if not api_key:
            logger.warning("[WorkoutWorker] OPENAI_API_KEY not configured — sandbox fallback")
            async for chunk in self._stream_sandbox(_MOCK_WORKOUT):
                yield chunk
            yield "data: [DONE]\n\n"
            return

        system_prompt = self._merge_context(WORKOUT_SYSTEM_PROMPT, user_context)
        user_content = self._build_user_content(user_message, kwargs)

        goal = kwargs.get("goal", "hypertrophy")
        experience = kwargs.get("experience_level", "intermediate")
        split = kwargs.get("split", "push_pull_legs")
        equipment = kwargs.get("equipment", "gym")

        logger.info(
            "[WorkoutWorker] Streaming: goal=%s experience=%s split=%s equipment=%s context=%s",
            goal, experience, split, equipment,
            "yes" if user_context else "none",
        )

        guard = AgentLoopGuard(max_iterations=_MAX_STREAM_CHUNKS)
        client = AsyncOpenAI(api_key=api_key)

        try:
            stream = await client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_content},
                ],
                stream=True,
                temperature=0.7,
                max_tokens=3000,
            )

            async for chunk in stream:
                try:
                    guard.tick()
                except MaxIterationsExceededError:
                    logger.warning(
                        "[WorkoutWorker] Stream terminated: budget exceeded after %d chunks",
                        guard.current,
                    )
                    yield self._sse({"error": True, "message": "Generation terminated: maximum output length reached"})
                    break
                delta = chunk.choices[0].delta if chunk.choices else None
                if delta and delta.content:
                    yield self._sse({"text": delta.content})

        except _OPENAI_ERRORS as exc:
            logger.warning(
                "[WorkoutWorker] OpenAI unavailable (%s: %s) — sandbox fallback",
                type(exc).__name__, exc,
            )
            async for chunk in self._stream_sandbox(_MOCK_WORKOUT):
                yield chunk

        except Exception:
            logger.exception("[WorkoutWorker] Unexpected error during streaming")
            async for chunk in self._stream_sandbox(_MOCK_WORKOUT):
                yield chunk

        yield "data: [DONE]\n\n"

    # ── Internal Helpers ───────────────────────────────────────────────

    def _merge_context(self, base: str, context: UserAIContext | None) -> str:
        """Merge user context into the system prompt."""
        if context is None:
            return base
        block = context.format_for_prompt()
        if not block:
            return base
        return f"{base}\n\n{_CONTEXT_HEADER}\n{block}"

    def _build_user_content(self, raw_message: str, kwargs: dict) -> str:
        """Build structured user content from raw message and kwargs."""
        goal_labels = {
            "strength": "Maximum Strength",
            "hypertrophy": "Muscle Hypertrophy",
            "endurance": "Muscular Endurance",
            "fat_loss": "Fat Loss & Conditioning",
        }
        split_labels = {
            "upper_lower": "Upper/Lower Split",
            "push_pull_legs": "Push/Pull/Legs Split",
            "full_body": "Full Body Training",
        }
        equipment_labels = {
            "gym": "Full Gym (barbells, cables, machines)",
            "bodyweight": "Bodyweight Only",
            "dumbbells": "Dumbbells + Basic Equipment",
        }

        parts: list[str] = []

        if kwargs.get("goal"):
            parts.append(f"- Primary Goal: {goal_labels.get(kwargs['goal'], kwargs['goal'])}")
        if kwargs.get("experience_level"):
            parts.append(f"- Experience Level: {kwargs['experience_level'].capitalize()}")
        if kwargs.get("split"):
            parts.append(f"- Training Split: {split_labels.get(kwargs['split'], kwargs['split'])}")
        if kwargs.get("equipment"):
            parts.append(f"- Equipment Available: {equipment_labels.get(kwargs['equipment'], kwargs['equipment'])}")

        if parts:
            return (
                "Generate a complete workout program with the following specifications:\n\n"
                + "\n".join(parts)
                + "\n\n"
                + raw_message
            )
        return raw_message

    async def _stream_sandbox(self, text: str) -> AsyncGenerator[str, None]:
        """Yield text in chunks for mock streaming."""
        yield self._sse({"sandbox": True, "text": ""})
        chunk_size = 8
        for i in range(0, len(text), chunk_size):
            yield self._sse({"text": text[i : i + chunk_size]})
            await asyncio.sleep(_MOCK_CHUNK_DELAY)

    @staticmethod
    def _sse(data: dict) -> str:
        """Format data as an SSE line."""
        return f"data: {json.dumps(data)}\n\n"
