import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import { ThemeProvider } from "next-themes";

import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";
import { CookieBanner } from "@/components/ui/cookie-banner";
import { ScrollProgress } from "@/components/ui/scroll-progress";
import { LenisProvider } from "@/components/lenis-provider";
// TEMPORARILY DISABLED — PostHog analytics paused (see provider POSTHOG_ENABLED flag).
// import { PostHogProvider } from "@/components/providers/posthog-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAFAF9" },
    { media: "(prefers-color-scheme: dark)", color: "#09090B" },
  ],
  width: "device-width",
  initialScale: 1,
};

// Canonical origin MUST match Vercel's primary domain (www redirects from
// the apex). Mismatched URLs here make Google crawl apex URLs that 308-redirect
// to www, which shows up in Search Console as "Page with redirect" and splits
// canonical signals.
const SITE_URL = "https://www.southasianfitness.com";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "South Asian Fitness | AI Meal Plans & Macro Tracking",
    template: "%s | South Asian Fitness",
  },
  description:
    "Stop guessing your macros. Get personalized, AI-driven meal plans " +
    "featuring the South Asian foods you actually eat.",
  keywords: [
    "South Asian fitness",
    "Indian meal plan",
    "Pakistani diet",
    "cultural nutrition tracker",
    "Biryani macros",
    "AI meal planner",
    "Desi fitness",
    "macro tracker",
  ],
  authors: [{ name: "South Asian Fitness" }],
  creator: "South Asian Fitness",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "South Asian Fitness",
    title: "South Asian Fitness | AI Meal Plans & Macro Tracking",
    description:
      "Stop guessing your macros. Get personalized, AI-driven meal plans " +
      "featuring the South Asian foods you actually eat.",
    // og:image is auto-generated by the App Router file convention:
    // app/opengraph-image.png (1200x630). No explicit images entry needed.
  },
  twitter: {
    card: "summary_large_image",
    title: "South Asian Fitness | AI Meal Plans & Macro Tracking",
    description:
      "Stop guessing your macros. Get personalized, AI-driven meal plans " +
      "featuring the South Asian foods you actually eat.",
    // twitter:image is auto-generated from app/opengraph-image.png as well.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // NOTE: no root-level alternates.canonical — a canonical set here would be
  // inherited by every page and point them all at the homepage. Pages that
  // need a canonical tag should declare their own in their local metadata.
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-background text-foreground">
        {/* TEMPORARILY DISABLED — PostHog analytics paused. */}
        {/* <PostHogProvider> */}
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange={false}
          >
            <a
              href="#main-content"
              className="sr-only focus:not-sr-only focus:absolute focus:z-50 focus:m-2 focus:rounded-lg focus:bg-white focus:px-4 focus:py-2 focus:text-stone-900 focus:outline-none focus:shadow-lg dark:focus:bg-zinc-900 dark:focus:text-zinc-100"
            >
              Skip to content
            </a>
            <ScrollProgress />
            <LenisProvider>
              <div id="main-content" className="flex-1 flex flex-col relative">
                <div className="relative z-10">
                {children}
              </div>
            </div>
            </LenisProvider>
            <CookieBanner />
          </ThemeProvider>
          {/* </PostHogProvider> — TEMPORARILY DISABLED */}
        <GoogleAnalytics gaId="G-XJ76SYV2L2" />
      </body>
    </html>
  );
}
