import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { LandingPage } from "@/components/landing-page";

/* Homepage SEO: `title.absolute` keeps the established SERP title (the root
   layout's "%s | South Asian Fitness" template would otherwise append the
   brand twice). Description/OG aligned with the landing hero messaging;
   og:image is auto-generated by app/opengraph-image.tsx. */
export const metadata: Metadata = {
  title: { absolute: "South Asian Fitness | AI Meal Plans & Macro Tracking" },
  description:
    "Track authentic Desi macros in seconds — AI meal plans with precise macros for Biryani, Daal, Roti, and 215+ South Asian dishes.",
  alternates: { canonical: "https://www.southasianfitness.com" },
  openGraph: {
    type: "website",
    url: "https://www.southasianfitness.com",
    siteName: "South Asian Fitness",
    title: "South Asian Fitness | AI Meal Plans & Macro Tracking",
    description:
      "Track authentic Desi macros in seconds — AI meal plans with precise macros for Biryani, Daal, Roti, and 215+ South Asian dishes.",
  },
  twitter: {
    card: "summary_large_image",
    title: "South Asian Fitness | AI Meal Plans & Macro Tracking",
    description:
      "Track authentic Desi macros in seconds — AI meal plans with precise macros for Biryani, Daal, Roti, and 215+ South Asian dishes.",
  },
};

/* Below-fold sections: dynamically imported to reduce initial JS bundle */
const LeadMagnetSection = dynamic(
  () =>
    import("@/components/sections/lead-magnet-section").then(
      (m) => m.LeadMagnetSection,
    ),
);

const TestimonialsSection = dynamic(
  () =>
    import("@/components/sections/testimonials-section").then(
      (m) => m.TestimonialsSection,
    ),
);

const FAQSection = dynamic(
  () =>
    import("@/components/sections/faq-section").then((m) => m.FAQSection),
);

/* Note: no `ssr: false` here — that option is not allowed with `next/dynamic`
 * in Server Components (Next 15). Both components are client components that
 * guard their browser-only APIs (window / scroll listeners) inside effects,
 * so server-rendering them is safe and keeps the dynamic code-splitting. */
const MobileStickyCTA = dynamic(
  () => import("@/components/ui/mobile-sticky-cta").then((m) => m.MobileStickyCTA),
);

const BackToTop = dynamic(
  () => import("@/components/ui/back-to-top").then((m) => m.BackToTop),
);

export default function Home() {
  return (
    <>
      <LandingPage />
      <LeadMagnetSection />
      <TestimonialsSection />
      <FAQSection />
      <MobileStickyCTA />
      <BackToTop />
    </>
  );
}
