"""add google_id column for oauth account linking

Revision ID: c895ba085173
Revises: 20260901_0010
Create Date: 2026-09-03 19:30:05.427239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c895ba085173'
down_revision: Union[str, Sequence[str], None] = '20260901_0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currencies', 'minor_units',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('food_sources', 'license_category',
               existing_type=postgresql.ENUM('public_domain', 'cc0', 'cc_by', 'cc_by_sa', 'open_data', 'proprietary_allow_redist', 'proprietary_no_redist', 'unknown', name='food_source_license'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('food_sources', 'can_store_raw_data',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('food_sources', 'can_store_derived_values',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('foods', 'translations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('foods', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('foods', 'verification_status',
               existing_type=postgresql.ENUM('unverified', 'pending_review', 'verified', 'conflict', 'retracted', 'verified_with_notes', 'rejected', name='verification_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('meal_foods', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('meal_plan_day_meals', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('meal_plans', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'completed', 'cancelled', name='meal_plan_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('meals', 'translations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('meals', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_user_sessions_token_hash'), 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_user_sessions_token_hash'), 'user_sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('meals', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('meals', 'translations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('meal_plans', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'completed', 'cancelled', name='meal_plan_status'),
               server_default=sa.text("'draft'::meal_plan_status"),
               existing_nullable=False)
    op.alter_column('meal_plan_day_meals', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('meal_foods', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('foods', 'verification_status',
               existing_type=postgresql.ENUM('unverified', 'pending_review', 'verified', 'conflict', 'retracted', 'verified_with_notes', 'rejected', name='verification_status'),
               server_default=sa.text("'unverified'::verification_status"),
               existing_nullable=False)
    op.alter_column('foods', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('foods', 'translations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('food_sources', 'can_store_derived_values',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('food_sources', 'can_store_raw_data',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('food_sources', 'license_category',
               existing_type=postgresql.ENUM('public_domain', 'cc0', 'cc_by', 'cc_by_sa', 'open_data', 'proprietary_allow_redist', 'proprietary_no_redist', 'unknown', name='food_source_license'),
               server_default=sa.text("'unknown'::food_source_license"),
               existing_nullable=False)
    op.alter_column('currencies', 'minor_units',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2'),
               existing_nullable=False)
    # ### end Alembic commands ###
